### ISSUE TITLE
Cant install this file 

### ISSUE THREAD

**Issue by clearmyskin** [SpeckyYT/SpeckyBot#7]
C:\Users\Administrator>npm install m3u8stream/lib/parse-time'
npm ERR! code ENOLOCAL
npm ERR! Could not install from "m3u8stream\lib\parse-time'" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-01-06T07_40_44_279Z-debug.log

**Comment by SpeckyYT** [comment]
I never had that problem before during installation.

I hope this StackOverflow forum may be helpful you...

https://stackoverflow.com/questions/58965713/cannot-find-module-m3u8stream-lib-parse-time/59022486#59022486
