### ISSUE TITLE
Nope still error didnt solved 

### ISSUE THREAD

**Issue by clearmyskin** [SpeckyYT/SpeckyBot#8]
const m3u8stream = require('m3u8stream');

const parseTime   = require('m3u8stream/dist/parse-time');

could you change ur line to this or provide me line so that i can change in mine console

**Comment by SpeckyYT** [comment]
Even GitHub CI had problems with the code above.
https://github.com/SpeckyYT/SpeckyBot/runs/375235504
I'll investigate a bit deeper.

**Comment by SpeckyYT** [comment]
I looked at the dependencies, but every dependency that uses m3u8stream require a different version of it. I have no idea how to "bypass" this problem...

**Comment by SpeckyYT** [comment]
Unknown error: By installing dependencies everything worked.
